### ISSUE TITLE
'“Project Aim” is damaged and can’t be opened. You should move it to the Bin.' Error message on M1 Mac

### ISSUE THREAD

**Issue by thecarefulcactus** [ahmadhayyan/project-aim#4]
after downloading project aim from your itch.io link and unzipping the file to open the program, the error { “Project Aim” is damaged and can’t be opened. You should move it to the Bin. } was displayed.
![Screenshot 2023-12-24 at 3 21 53 pm](https://github.com/ahmadhayyan/project-aim/assets/89644288/19c84ab0-3a1b-46e6-a145-d539c67e88d0)

**Comment by ahmadhayyan** [comment]
Hi,

We sincerely appreciate you bringing this matter to our attention. Your input is valuable to us, and we are grateful for your assistance in identifying this issue.

The issue at hand is probably due to the `.app` file being contained within a ZIP archive that has been downloaded from the internet, rather than the Mac App Store, making it untrusted by the MacOS.

To address this matter, you may follow the guidelines presented below:

1. Open a new Terminal window
2. Type `xattr -d com.apple.quarantine "/path/to/Project Aim.app"` and press enter

[Reference](https://www.howtogeek.com/803598/app-is-damaged-and-cant-be-opened/)

We hope that these instructions will aid in resolving the aforementioned issue.
Thank you.
