### ISSUE TITLE
App is damaged and can't be opened

### ISSUE THREAD

**Issue by senz** [ahmadhayyan/project-aim#6]
Sometimes you may encounter this error while trying to start the application.
Solution is to remove quarantine flag: `xattr -cr ~/Downloads/Project\ Aim.app`

Saw it [here](https://www.reddit.com/r/MacOS/comments/q9d772/comment/hh4vbgf).

I suggest to put this remark in readme.

**Comment by ahmadhayyan** [comment]
Hi,

We sincerely appreciate you bringing this matter to our attention. Your input is valuable to us, and we are grateful for your assistance in identifying this issue.

This issue is similar to [https://github.com/ahmadhayyan/project-aim/issues/4](https://github.com/ahmadhayyan/project-aim/issues/4).
The issue at hand is probably due to the `.app` file being contained within a ZIP archive that has been downloaded from the internet, rather than the Mac App Store, making it untrusted by the MacOS.

I am uncertain whether the information in question would be relevant for inclusion in the readme document as it is an issue from the MacOS side.

However, I would like to express my gratitude for the benevolent intentions you have shown. Your efforts are truly appreciated.
Thank you.
